version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/var/task:delegated
      - ~/.aws:/root/.aws
    ports:
      - "8080:8080"
      - "5680:5680"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
volumes:
  postgres_data: